version: '3'
services:
  aria2:
    container_name: aria2
    build: ./aria2
    ports:
      - "6800:6800"
    volumes:
      - /media/KINGSTON:/download
      - /var/log:/var/log
  aria-ng:
    container_name: aria-ng
    build: ./aria-ng
    ports:
      - "801:80"
      - "443:443"
    depends_on:
      - aria2
